### ISSUE TITLE
Elementos não clicavéis visualmente

### ISSUE THREAD

**Issue by martygo** [e200/devs.ao#10]
Olá, @e200. Na aba de menu para fazer filtros, as primeiras opções, o efeito do cursor, não indica ao usuário que é um elemento clicavél, pôs não aplica o efeito cursor: pointer.

Gravei um vídeo para melhor demonstrar: https://drive.google.com/file/d/1iSTCY0dDEOI91BJSc4DwsSSme_yr_msf/view?usp=sharing

**Comment by e200** [comment]
Uma PR seria bem-vinda. Otherwise só quando tiver tempo.

**Comment by martygo** [comment]
OK! Então será uma PR mesmo.
